use std::fs;
use std::path::PathBuf;
use chrono::Utc; // New import

const RESERVED_WORDS: &[&str] = &[
    "fn", "mod", "crate", "use", "impl", "struct", "enum", "async", "await", "dyn",
];

fn is_valid_rust_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => (),
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn is_valid_translation_file(content: &str) -> bool {
    content.contains("define_translations!") || content.contains("pub static TRANSLATIONS: Lazy<HashMap<")
        && !content.contains("fn")
        && !content.contains("mod")
        && !content.contains("struct")
        && !content.contains("enum")
}

fn main() {
    let lang_dir = PathBuf::from("src/lang");
    let output_file = lang_dir.join("generated_mod.rs");

    let mut modules = vec![];

    for entry in fs::read_dir(&lang_dir).expect("src/lang folder must exist") {
        let entry = entry.expect("Failed to read lang dir entry");
        let path = entry.path();
        if path.is_file() {
            if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
                if name != "mod"
                    && name != "generated_mod"
                    && is_valid_rust_identifier(name)
                    && !RESERVED_WORDS.contains(&name)
                {
                    let content = fs::read_to_string(&path).unwrap_or_default();
                    if is_valid_translation_file(&content) {
                        modules.push(name.to_string());
                    } else {
                        println!(
                            "cargo:warning=Ignoring '{}' because it does not define a valid TRANSLATIONS static",
                            name
                        );
                    }
                } else {
                    println!(
                        "cargo:warning=Ignoring invalid or reserved module name '{}'",
                        name
                    );
                }
            }
        }
    }

    let now = Utc::now();
    let mut code = String::new();

    // Insert the warning banner and timestamp
    code.push_str("// ===========================================================\n");
    code.push_str("// THIS FILE IS AUTO-GENERATED BY build.rs\n");
    code.push_str("// DO NOT EDIT THIS FILE MANUALLY — YOUR CHANGES WILL BE LOST!\n");
    code.push_str(&format!("// Generated: {}\n", now.to_rfc3339()));
    code.push_str("// ===========================================================\n\n");

    // Generate the modules
    for module in &modules {
        code.push_str(&format!("pub mod {};\n", module));
    }

    code.push_str("\nuse once_cell::sync::Lazy;\n");
    code.push_str("use std::collections::HashMap;\n\n");

    code.push_str("pub static TRANSLATION_REGISTRY: Lazy<HashMap<&'static str, &'static Lazy<HashMap<&'static str, &'static str>>>> = Lazy::new(|| {\n");
    code.push_str("    HashMap::from([\n");
    for module in &modules {
        code.push_str(&format!("        (\"{}\", &{}::TRANSLATIONS),\n", module, module));
    }
    code.push_str("    ])\n");
    code.push_str("});\n");

    fs::write(&output_file, code).expect("Failed to write src/lang/generated_mod.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/lang/");
}
