use std::fs;
use std::path::PathBuf;

fn main() {
    let lang_dir = PathBuf::from("lang");
    let output_file = PathBuf::from("src/lang/generated_mod.rs");

    let mut modules = vec![];
    let mut runtime_locales = vec![];

    if !lang_dir.exists() {
        println!("cargo:warning=lang/ directory not found, skipping generated_mod.rs creation");
        return;
    }

    for entry in fs::read_dir(&lang_dir).expect("Failed to read lang/ folder") {
        let entry = entry.expect("Failed to read lang file entry");
        let path = entry.path();

        if path.is_file() {
            let filename = path.file_name().unwrap().to_string_lossy();

            if filename.ends_with(".rs") {
                if let Some(locale) = path.file_stem().and_then(|s| s.to_str()) {
                    modules.push(locale.to_string());
                }
            } else if filename.ends_with(".json")
                || filename.ends_with(".yaml")
                || filename.ends_with(".yml")
                || filename.ends_with(".toml")
            {
                if let Some(locale) = path.file_stem().and_then(|s| s.to_str()) {
                    runtime_locales.push(locale.to_string());
                }
            }
        }
    }

    // Generate the output
    let mut code = String::new();

    // Warning Banner
    code.push_str("// ===========================================================\n");
    code.push_str("// THIS FILE IS AUTO-GENERATED BY build.rs\n");
    code.push_str("// DO NOT EDIT THIS FILE MANUALLY — YOUR CHANGES WILL BE LOST!\n");
    code.push_str("// ===========================================================\n\n");

    // Module Imports
    for module in &modules {
        code.push_str(&format!("pub mod {};\n", module));
    }

    code.push_str("\nuse once_cell::sync::Lazy;\n");
    code.push_str("use std::collections::HashMap;\n");
    code.push_str("use crate::translate::load_translations;\n\n");

    code.push_str("pub static TRANSLATION_REGISTRY: Lazy<HashMap<&'static str, Lazy<HashMap<&'static str, &'static str>>>> = Lazy::new(|| {\n");
    code.push_str("    HashMap::from([\n");

    for module in &modules {
        code.push_str(&format!("        (\"{}\", Lazy::new(|| {}::translations())),\n", module, module));
    }
    for locale in &runtime_locales {
        code.push_str(&format!("        (\"{}\", Lazy::new(|| load_translations(\"{}\"))),\n", locale, locale));
    }

    code.push_str("    ])\n");
    code.push_str("});\n");

    fs::write(output_file, code).expect("Failed to write src/lang/generated_mod.rs");

    println!("cargo:rerun-if-changed=lang/");
    println!("cargo:rerun-if-changed=build.rs");
}
