// ===========================================================
// THIS FILE IS AUTO-GENERATED BY build.rs
// DO NOT EDIT THIS FILE MANUALLY — YOUR CHANGES WILL BE LOST!
// ===========================================================

pub mod en;
pub mod es;

use once_cell::sync::Lazy;
use std::collections::HashMap;
use crate::translate::load_translations;

pub static TRANSLATION_REGISTRY: Lazy<HashMap<&'static str, Lazy<HashMap<&'static str, &'static str>>>> = Lazy::new(|| {
    HashMap::from([
        ("en", Lazy::new(|| en::translations())),
        ("es", Lazy::new(|| es::translations())),
    ])
});
