// ===========================================================
// THIS FILE IS AUTO-GENERATED BY build.rs
// DO NOT EDIT THIS FILE MANUALLY — YOUR CHANGES WILL BE LOST!
// Generated: 2025-04-29T13:18:41.981195+00:00
// ===========================================================

pub mod en;
pub mod es;

use once_cell::sync::Lazy;
use std::collections::HashMap;

pub static TRANSLATION_REGISTRY: Lazy<HashMap<&'static str, &'static Lazy<HashMap<&'static str, &'static str>>>> = Lazy::new(|| {
    HashMap::from([
        ("en", &en::TRANSLATIONS),
        ("es", &es::TRANSLATIONS),
    ])
});
